ignore_path_regex:
  - .*(/doc/).*
  - .*(example).*
  - .*(version).*

test_regex:
  - .*(test).*

# consider renaming to 'source_dir_names'
include_path_regex:
  - .*(ophyd).*

extra_setup_files_regex:
  - .*(setup).*

generate_test_suite: True

blacklist_packages:
  - find_with_code
  - ConfigParser
  - versioneer
  - pkg_resources
